networks:
  infra_net:
    external: true

x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 1s
    timeout: 2s
    retries: 100
  networks:
    - infra_net

services:
  b-gateway:
    container_name: b-gateway
    <<: *baseService
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      b-backend:
        condition: service_healthy
      b-frontend:
        condition: service_healthy

  b-backend:
    container_name: b-backend
    <<: *baseService
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    devices:
        # - /dev/ttyUSB0:/dev/ttyUSB0 # Plaque CUxx
        - /dev/hidraw1:/dev/hidraw1 # lecteur HID (seulement pour PC de dev)
        - /dev/bus/usb:/dev/bus/usb # lecteur PCSC Exer
    depends_on:
      b-database:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://b-backend:3001/api/health' || exit 1",
        ]
    volumes:
      - ./backend/src:/app/src/
      - /run/pcscd:/run/pcscd
    environment:
      BADGE_TYPE: ${BADGE_TYPE}
      LOCKER_TYPE: ${LOCKER_TYPE}
      NFC_TYPE: ${NFC_TYPE}
      SERIAL_TYPE: ${SERIAL_TYPE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      # SERIAL_PATH: ${SERIAL_PATH}
      # TIMEOUT_STATUS: ${TIMEOUT_STATUS}
      # TIMEOUT_RESERVATION: ${TIMEOUT_RESERVATION}

  b-frontend:
    container_name: b-frontend
    <<: *baseService
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://b-frontend:5173' || exit 1",
        ]
    volumes:
      - ./frontend/src:/app/src/
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_WS_URL: ${VITE_WS_URL}

  b-database:
    container_name: b-database
    <<: *baseService
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    volumes:
      - ./persist/db-dev:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}

  b-adminer:
    <<: *baseService
    container_name: b-adminer
    image: adminer
    depends_on:
      b-database:
        condition: service_healthy
    command:
      [
        "php",
        "-d",
        "post_max_size=500M",
        "-d",
        "upload_max_filesize=500M",
        "-S",
        "0.0.0.0:8080",
        "-t",
        "/var/www/html",
      ]
